os:
 - linux

dist: trusty
sudo: false
addons:
 apt:
  sources:
   - sourceline: "deb http://archive.ubuntu.com/ubuntu trusty universe"
  packages:
   - libxinerama-dev
   - libxrandr-dev

language: c
compiler:
 - gcc
 - clang

script: make xcb=0 && ./xdpi
